caracteristicas_perros = {
    "Mastín": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Border Collie": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Beagle": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Labrador Retriever": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Golden Retriever": {"Comportamiento": "Curioso", "Tamaño": "Grande"},
    "Chihuahua": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Pastor Alemán": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Bulldog": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Caniche": {"Comportamiento": "Curioso", "Tamaño": "Mediano/Pequeño"},
    "Boxer": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Dálmata": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Doberman": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Rottweiler": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Husky Siberiano": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Cocker Spaniel": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Bichón Frisé": {"Comportamiento": "Tranquilo", "Tamaño": "Pequeño"},
    "Shih Tzu": {"Comportamiento": "Tranquilo", "Tamaño": "Pequeño"},
    "Yorkshire Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Pastor Australiano": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Pitbull": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Bulldog Francés": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Pomerania": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Akita Inu": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Shiba Inu": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Galgo": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Cavalier King Charles Spaniel": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Samoyedo": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Pointer": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Setter Irlandés": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Braco de Weimar": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "San Bernardo": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Terranova": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Basset Hound": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Pug": {"Comportamiento": "Tranquilo", "Tamaño": "Pequeño"},
    "Jack Russell Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Shar Pei": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Whippet": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Maltese": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Papillón": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Airedale Terrier": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Cane Corso": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Collie": {"Comportamiento": "Curioso", "Tamaño": "Grande"},
    "Dogo Argentino": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Fox Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño/Mediano"},
    "Gran Danés": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Lhasa Apso": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Pastor de Shetland": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Staffordshire Bull Terrier": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Teckel": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Vizsla": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Bloodhound": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Borzoi": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Bulldog Americano": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Chow Chow": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Clumber Spaniel": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Crestado Chino": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Dogo de Burdeos": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Fila Brasileiro": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Galgo Italiano": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Glen of Imaal Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Gordon Setter": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Irish Wolfhound": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Keeshond": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Kerry Blue Terrier": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "King Charles Spaniel": {"Comportamiento": "Tranquilo", "Tamaño": "Pequeño"},
    "Kooikerhondje": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Kuvasz": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Leonberger": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Löwchen": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Mudi": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Norfolk Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Norwich Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Old English Sheepdog": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Otterhound": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Parson Russell Terrier": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Pequeño Basset Griffon Vendeano": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Perro de Agua Español": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Perro de Agua Portugués": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Perro Lobo de Saarloos": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Pinscher Miniatura": {"Comportamiento": "Energético", "Tamaño": "Pequeño"},
    "Podenco Ibicenco": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Puli": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Pumi": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Rafeiro do Alentejo": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Retriever de Pelo Rizado": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Saluki": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Schnauzer Gigante": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Schnauzer Miniatura": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Scottish Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Sealyham Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Setter Gordon": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Silky Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Skye Terrier": {"Comportamiento": "Tranquilo", "Tamaño": "Pequeño"},
    "Sloughi": {"Comportamiento": "Energético", "Tamaño": "Grande"},
    "Spaniel de Sussex": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Spaniel Tibetano": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Spinone Italiano": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Springer Spaniel Galés": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Stabyhoun": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Staffordshire Terrier Americano": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Tibetan Mastiff": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Tibetan Terrier": {"Comportamiento": "Curioso", "Tamaño": "Mediano"},
    "Tosa": {"Comportamiento": "Tranquilo", "Tamaño": "Grande"},
    "Welsh Terrier": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "West Highland White Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"},
    "Whippet": {"Comportamiento": "Energético", "Tamaño": "Mediano"},
    "Xoloitzcuintle": {"Comportamiento": "Tranquilo", "Tamaño": "Mediano"},
    "Yorkshire Terrier": {"Comportamiento": "Curioso", "Tamaño": "Pequeño"}
}